"""RL-SERIES v2 (2026-09-16): collect every result file into the tables
that go into rl2-audit.md.

  python plan/rl2/report.py > plan/rl2/out/report.md
"""
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
RES = HERE / "results"
OUT = HERE / "out"

COLS = ["label", "days", "tickets", "total", "per_ticket", "tickets_per_day",
        "sharpe", "max_dd", "win_rate", "ext_exit_n", "ext_exit_pnl",
        "rth_exit_n", "rth_exit_pnl", "mean_hold", "forced"]
HDR = ["policy", "days", "tickets", "total $", "$/tkt", "tkt/day", "Sharpe",
       "max DD", "win%", "ext n", "ext $", "rth n", "rth $", "hold", "forced"]


def row(d):
    o = []
    for c in COLS:
        v = d.get(c, "")
        if c in ("total", "max_dd", "ext_exit_pnl", "rth_exit_pnl"):
            o.append(f"{v:,.0f}" if isinstance(v, (int, float)) else str(v))
        elif c == "win_rate":
            o.append(f"{v*100:.1f}" if isinstance(v, (int, float)) else str(v))
        else:
            o.append(str(v))
    return "| " + " | ".join(o) + " |"


def table(rows):
    out = ["| " + " | ".join(HDR) + " |",
           "|" + "---|" * len(HDR)]
    out += [row(r) for r in rows]
    return "\n".join(out)


def load(pat):
    out = []
    for p in sorted(RES.glob(pat)):
        d = json.loads(p.read_text())
        d["_file"] = p.stem
        out.append(d)
    return out


def main():
    print("# RL v2 result tables (generated by plan/rl2/report.py)\n")

    hp = OUT / "honesty.json"
    if hp.exists():
        h = json.loads(hp.read_text())
        print("## Honesty battery\n")
        print(f"- poison: **{h['poison']['checks']} checks, "
              f"{h['poison']['mismatches']} mismatches**")
        print(f"- hold-is-zero: {h['hold_zero']}")
        print(f"- cost monotonicity: {h['cost_monotone']}")
        rows = [h["foresight_30"], h.get("foresight_30_nothresh", {})]
        print("\n" + table([r for r in rows if r]) + "\n")
        print("Random controls (30 seeds each, 60 sampled test days):\n")
        print("| control | mean $/tkt | min | max | tkt/day |")
        print("|---|---|---|---|---|")
        for k, v in h.items():
            if k.startswith("random_"):
                print(f"| {k} | {v['mean_per_ticket']:.2f} | "
                      f"{v['min_per_ticket']:.2f} | {v['max_per_ticket']:.2f} "
                      f"| {v['mean_tickets_per_day']} |")
        print()

    pu = OUT / "profile_universe.json"
    if pu.exists():
        p = json.loads(pu.read_text())
        print("## The universe with no policy ($ per $15k ticket)\n")
        print("| split | H | all | RTH | EXT |")
        print("|---|---|---|---|---|")
        for sp in ("train", "val", "test"):
            t = p["per_ticket_by_horizon_and_session"].get(sp, {})
            for H in (15, 30, 60, 120, 1000000):
                a = t.get(f"{H}_all")
                if not a:
                    continue
                print(f"| {sp} | {H} | {a['per_ticket']} | "
                      f"{t[f'{H}_rth']['per_ticket']} | "
                      f"{t[f'{H}_ext']['per_ticket']} |")
        print()

    for name, pat in (("Approach 1 - contextual bandit", "bandit_*.json"),
                      ("Approach 2 - offline RL", "offline_*.json"),
                      ("Approach 3 - online RL", "rl_*.json"),
                      ("Approach 4 - rule search", "rules_*.json")):
        rows = load(pat)
        if not rows:
            continue
        print(f"## {name}\n")
        flat = []
        for r in rows:
            if "train" in r and isinstance(r["train"], dict):
                for s in ("train", "val", "test"):
                    if s in r and isinstance(r[s], dict) and r[s].get("days"):
                        d = dict(r[s])
                        d["label"] = f"{r['_file']} :: {s}"
                        flat.append(d)
            elif "heldout" in r:
                for s in ("train", "heldout"):
                    d = dict(r[s])
                    d["label"] = f"{r['_file']} :: {s}"
                    flat.append(d)
            elif "walkforward" in r:
                d = dict(r["walkforward"])
                d["label"] = r["_file"]
                flat.append(d)
            else:
                d = dict(r)
                d["label"] = r["_file"]
                flat.append(d)
        print(table(flat) + "\n")

    b = load("bandit_real_h30_s*.json")
    b = [r for r in b if r.get("min_pred") == 0.0]
    if len(b) > 1:
        t = np.array([r["total"] for r in b])
        pt = np.array([r["per_ticket"] for r in b])
        print(f"**Bandit seed spread (real, h=30, {len(b)} seeds):** total "
              f"{t.min():,.0f} … {t.max():,.0f}, $/ticket {pt.min():.2f} … "
              f"{pt.max():.2f}, mean {pt.mean():.2f}\n")
    if b:
        print("### Per-test-month (bandit real h=30 seed 0)\n")
        r0 = [r for r in b if r["seed"] == 0]
        if r0:
            print("| month | tickets | total $ | $/tkt | Sharpe |")
            print("|---|---|---|---|---|")
            for m in r0[0]["per_month"]:
                print(f"| {m['label']} | {m['tickets']} | {m['total']:,.0f} | "
                      f"{m['per_ticket']:.2f} | {m['sharpe']} |")
            print()
            if "feature_gain" in r0[0]:
                print("Top features by gain (last fold): "
                      + ", ".join(f"{a} ({g:,.0f})"
                                  for a, g in r0[0]["feature_gain"][:8]) + "\n")


if __name__ == "__main__":
    main()
