"""MX-series runner (2026-09-02): mean-reversion entry on gappers with
TA-triggered sells inside a 10:30-12:00 exit window. Pre-registration
and priors: NOTES-DAYTRADING.md "MX-SERIES PRE-REGISTRATION".

The configs live in plan/rotation_sim.py (CFGS, generated by _mx_cfgs).
This file only (a) launches shards with the standing honesty
environment, (b) reads the mean hold of a ranked config for its -S
control, and (c) aggregates rotation_results_mx_*.json into the table,
control percentiles, the exit x window adjacency grid and the verdicts.

  python plan/mx_series.py launch <shard> <cfg> [cfg ...] [--labels L]
                                  [--reps 0-29] [--hold N] [--days N]
  python plan/mx_series.py hold <cfg>          # mean hold, minutes
  python plan/mx_series.py table [--out FILE]  # the aggregate

Env used by every launch: HALAL_STRICT=1 PT_FILED=1 POOL_HYGIENE=1
ROTTRADES=1 MASSIVE_TH_INTERVAL=0.25; ROTSHARD=mx_<shard>; ROTLABELS,
ROTREP, MXHOLD as given. Logs: /c/tmp/mx/<shard>.log; a shard is done
when data/massive/rotation_results_mx_<shard>.json exists.
"""
import glob
import json
import os
import re
import statistics as st
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = Path("C:/tmp/mx")
ENV = dict(HALAL_STRICT="1", PT_FILED="1", POOL_HYGIENE="1", ROTTRADES="1",
           MASSIVE_TH_INTERVAL="0.25")
WINS = ("1030", "1100", "1130", "1200")
EXITS = ("H", "V", "R", "M", "B", "P", "VB", "T")


def _arg(argv, flag, default=None):
    if flag in argv:
        i = argv.index(flag)
        v = argv[i + 1]
        del argv[i:i + 2]
        return v
    return default


def launch(argv):
    labels = _arg(argv, "--labels")
    reps = _arg(argv, "--reps")
    hold = _arg(argv, "--hold")
    days = _arg(argv, "--days")
    shard, cfgs = argv[0], argv[1:]
    env = dict(os.environ, **ENV, ROTSHARD=f"mx_{shard}")
    if labels:
        env["ROTLABELS"] = labels
    if reps:
        env["ROTREP"] = reps
    if hold:
        # "N" (all configs) or "CFG=N,CFG=N" (per-config MXHOLD_<cfg>)
        if "=" in hold:
            for part in hold.split(","):
                c, n = part.split("=")
                env[f"MXHOLD_{c}"] = n
            env.setdefault("MXHOLD", "0")
        else:
            env["MXHOLD"] = str(hold)
    LOG.mkdir(parents=True, exist_ok=True)
    cmd = [sys.executable, str(ROOT / "plan/rotation_sim.py")] + cfgs
    if days:
        cmd += ["--days", days]
    out = open(LOG / f"{shard}.log", "w")
    p = subprocess.Popen(cmd, cwd=str(ROOT), env=env, stdout=out,
                         stderr=subprocess.STDOUT,
                         creationflags=getattr(subprocess,
                                               "CREATE_NEW_PROCESS_GROUP", 0))
    print(f"launched mx_{shard} pid {p.pid}: {' '.join(cfgs)} "
          f"labels={labels or 'year,y2025'} reps={reps or '-'} "
          f"hold={hold or '-'}")


def mean_hold(cfg):
    fs = glob.glob(str(ROOT / f"data/massive/rotation_trades_{cfg}_mx_*.json"))
    mins = []
    for f in fs:
        for x in json.load(open(f)):
            if x.get("label") == "aug2026":
                continue
            a, b = x["entry_time"], x["exit_time"]
            import pandas as pd
            mins.append((pd.Timestamp(b) - pd.Timestamp(a)).total_seconds() / 60)
    return (sum(mins) / len(mins)) if mins else None, len(mins)


def load():
    res = {}
    for f in sorted(glob.glob(str(ROOT / "data/massive/rotation_results_mx_*.json"))):
        for k, v in json.load(open(f)).items():
            labs = v.get("labels") or []
            key = k + ("@aug" if labs == ["aug2026"] else "")
            res[key] = v
    return res


def agg(v):
    labs = [l for l in ("year", "y2025", "aug2026") if l in v]
    if not labs:
        return None
    o = dict(total=sum(v[l]["total"] for l in labs),
             Y1=v[labs[0]]["total"],
             Y2=v[labs[1]]["total"] if len(labs) > 1 else None,
             days=sum(v[l]["days"] for l in labs),
             tickets=sum(v[l]["tickets"] for l in labs),
             deployed=sum(v[l]["deployed"] for l in labs),
             negm=sum(v[l]["negm"] for l in labs),
             nm=sum(v[l]["nmonths"] for l in labs),
             maxdd=max(v[l]["max_dd"] for l in labs),
             best=max(v[l]["best_day"] for l in labs),
             worst=min(v[l]["worst_day"] for l in labs))
    o["ex_best"] = o["total"] - o["best"]
    o["pt"] = o["total"] / o["tickets"] if o["tickets"] else 0.0
    o["pt1"] = (v[labs[0]]["total"] / v[labs[0]]["tickets"]
                if v[labs[0]]["tickets"] else 0.0)
    o["pt2"] = ((v[labs[1]]["total"] / v[labs[1]]["tickets"])
                if len(labs) > 1 and v[labs[1]]["tickets"] else None)
    hs = [v[l].get("mean_hold_min") for l in labs if v[l].get("mean_hold_min")]
    o["hold"] = sum(hs) / len(hs) if hs else None
    o["exits"] = {}
    for l in labs:
        for k2, e in v[l].get("exit_reasons", {}).items():
            a = o["exits"].setdefault(k2, [0, 0])
            a[0] += e["n"]
            a[1] += e["pnl"]
    return o


def pct(x, d):
    return 100 * sum(1 for y in d if y < x) / len(d) if d else None


def table(argv):
    outf = _arg(argv, "--out")
    res = load()
    rows = {k: agg(v) for k, v in res.items()}
    rows = {k: o for k, o in rows.items() if o}
    ctrl = {}
    for k, o in rows.items():
        if "#r" in k:
            ctrl.setdefault(re.sub(r"#r\d+", "", k), []).append(o)
    lines = []
    P = lines.append
    ranked = [k for k in rows if "#r" not in k and "@aug" not in k
              and not k.endswith(("-R", "-I", "-S"))]
    hdr = ("config", "total", "Y1", "Y2", "days", "tkts", "$/tkt", "$/t Y1",
           "$/t Y2", "negm", "maxDD", "best", "worst", "ex_best", "hold_m")
    P(" ".join(f"{h:>9}" for h in hdr))

    def f(x, s="+,.0f"):
        return "-" if x is None else format(x, s)
    order = ["C37F"] + sorted(k for k in ranked if k != "C37F")
    for k in order:
        if k not in rows:
            continue
        o = rows[k]
        P(" ".join(f"{s:>9}" for s in (
            k, f(o["total"]), f(o["Y1"]), f(o["Y2"]), o["days"], o["tickets"],
            f(o["pt"]), f(o["pt1"]), f(o["pt2"]), f"{o['negm']}/{o['nm']}",
            f"{o['maxdd']:,}", f(o["best"]), f(o["worst"]), f(o["ex_best"]),
            f(o["hold"], ".0f"))))
        P(f"{'':>9} exits: " + "  ".join(
            f"{a}:{b[0]}/${b[1]:+,}" for a, b in sorted(o["exits"].items())))
    # ---- adjacency grid: $/ticket by exit rule x window, per entry family
    for fam in sorted({k[:3] for k in ranked if k[:2] in ("MX", "MT")}):
        P("")
        P(f"ADJACENCY {fam} ($/ticket both years; tickets in brackets)")
        P(" ".join(f"{h:>16}" for h in ("exit",) + WINS))
        for x in EXITS:
            cells = []
            for w in WINS:
                k = f"{fam}{w}{x}"
                o = rows.get(k)
                cells.append(f"{o['pt']:+.0f} [{o['tickets']}]" if o else "-")
            P(" ".join(f"{c:>16}" for c in ((x,) + tuple(cells))))
    # ---- controls
    P("")
    for c, dist in sorted(ctrl.items()):
        base = re.sub(r"-[RS]$", "", c)
        kind = "random pick" if c.endswith("-R") else "shuffled exit"
        o = rows.get(base)
        tot = sorted(d["total"] for d in dist)
        exb = sorted(d["ex_best"] for d in dist)
        pt = sorted(d["pt"] for d in dist)
        y1 = sorted(d["Y1"] for d in dist)
        y2 = sorted(d["Y2"] for d in dist if d["Y2"] is not None)
        P(f"{c} ({kind}, n={len(dist)}): total median {st.median(tot):+,.0f} "
          f"[{tot[0]:+,} .. {tot[-1]:+,}]  ex_best median {st.median(exb):+,.0f}"
          f"  $/tkt median {st.median(pt):+.0f}  negm median "
          f"{st.median(d['negm'] for d in dist)}")
        if o:
            P(f"   {base}: total pctile {pct(o['total'], tot):.0f} | ex_best "
              f"pctile {pct(o['ex_best'], exb):.0f} | $/tkt pctile "
              f"{pct(o['pt'], pt):.0f} | Y1 pctile {pct(o['Y1'], y1):.0f}"
              + (f" | Y2 pctile {pct(o['Y2'], y2):.0f}"
                 if o["Y2"] is not None and y2 else ""))
    for k in sorted(k for k in rows if k.endswith("-I")):
        o, b = rows[k], rows.get(k[:-2])
        P(f"{k} (inverted): total {o['total']:+,} $/tkt {o['pt']:+.0f}"
          + (f"   vs ranked {b['total']:+,} / {b['pt']:+.0f}" if b else ""))
    augs = sorted(k for k in rows if k.endswith("@aug") and "#r" not in k)
    if augs:
        P("")
        P("AUGUST 2026 OUT-OF-SAMPLE")
        for k in augs:
            o = rows[k]
            P(f"  {k[:-4]:<12} total {o['total']:+,} days {o['days']} tkts "
              f"{o['tickets']} $/tkt {o['pt']:+.0f} ex_best {o['ex_best']:+,}")
        for c, dist in sorted(ctrl.items()):
            if not c.endswith("@aug"):
                continue
            base = re.sub(r"-[RS]@aug$", "", c)
            o = rows.get(base + "@aug")
            tot = sorted(d["total"] for d in dist)
            pt = sorted(d["pt"] for d in dist)
            P(f"  {c} n={len(dist)} median {st.median(tot):+,.0f} "
              f"[{tot[0]:+,} .. {tot[-1]:+,}]"
              + (f"; {base}@aug pctile total {pct(o['total'], tot):.0f} "
                 f"$/tkt {pct(o['pt'], pt):.0f}" if o else ""))
    # ---- verdict scan against the pre-registered bar
    P("")
    P("PASS-BAR SCAN (both years $/tkt > 0; beats C37F-fm -56/tkt; "
      ">=90th pctile of -R on total AND ex_best; -I loses; -S median beaten)")
    for k in order:
        if k == "C37F" or k not in rows:
            continue
        o = rows[k]
        both = o["pt1"] > 0 and (o["pt2"] is not None and o["pt2"] > 0)
        beats = o["pt"] > -56
        r = ctrl.get(k + "-R")
        s_ = ctrl.get(k + "-S")
        inv = rows.get(k + "-I")
        pr = (pct(o["total"], sorted(d["total"] for d in r)),
              pct(o["ex_best"], sorted(d["ex_best"] for d in r))) if r else None
        ps = pct(o["total"], sorted(d["total"] for d in s_)) if s_ else None
        flags = [f"both_years={'Y' if both else 'n'}",
                 f"beats_C37F={'Y' if beats else 'n'}",
                 f"R_pct={'-' if pr is None else f'{pr[0]:.0f}/{pr[1]:.0f}'}",
                 f"I_loses={'-' if inv is None else ('Y' if inv['total'] < o['total'] else 'n')}",
                 f"S_pct={'-' if ps is None else f'{ps:.0f}'}"]
        ok = (both and beats and pr is not None and min(pr) >= 90
              and inv is not None and inv["total"] < o["total"]
              and (ps is None or ps >= 50))
        P(f"  {k:<11} {o['pt']:+7.0f}/tkt  " + "  ".join(flags)
          + ("  <-- PASSES" if ok else ""))
    txt = "\n".join(lines)
    print(txt)
    if outf:
        Path(outf).write_text(txt, encoding="utf-8")


if __name__ == "__main__":
    a = sys.argv[1:]
    if not a:
        print(__doc__)
    elif a[0] == "launch":
        launch(a[1:])
    elif a[0] == "hold":
        m, n = mean_hold(a[1])
        print(f"{a[1]}: mean hold {m:.1f} min over {n} legs -> MXHOLD "
              f"{round(2 * m)}" if m else f"{a[1]}: no legs")
    elif a[0] == "table":
        table(a[1:])
    else:
        print(__doc__)
